### ISSUE TITLE
new identity : Uncaught TypeError: Unsupported operand types: null + array

### ISSUE THREAD

**Issue by ebinet** [deflomu/Roundcube-SMTP-per-Identity-Plugin#24]
When creating a new identity :
`PHP Fatal error:  Uncaught TypeError: Unsupported operand types: null + array in /path-to-roundcube/plugins/identity_smtp/identity_smtp.php:194`

If I insrt this new line just before line 194 it seems to work again :
`if (is_null($record)) $record = array();`

Roundcube version = 1.5.2
php version = 8.0
identity_smtp branch = master

**Comment by Jan-E** [comment]
Could this be related to https://github.com/deflomu/Roundcube-SMTP-per-Identity-Plugin/pull/23/commits/411a33432ab1ba7fdb6004f6b2b66bd3601dff9f ?

**Comment by ebinet** [comment]
Yes indeed. I saw the pull request just after opening my issue. It would be useful to go forward. The code proposed isn't very different from mine.

**Comment by NotActuallyTerry** [comment]
Fixed by #23
