### ISSUE TITLE
After upgrade to Roundcube 1.5.2 always SMTP server from config.inc.php is used

### ISSUE THREAD

**Issue by mercury1337** [deflomu/Roundcube-SMTP-per-Identity-Plugin#27]
I upgraded to RCM 1.5.2 and since then the plugin does no longer work for me.
After the upgrade the SMTP server strings were empty in RCM and I had to add them again. But then I noticed that no matter what I had configured always the SMTP server from config.inc.php is used (had to enable SMTP debugging to see the problem in the logs)
Enabling / disabling identities did not help and also adding new ones shows the same behavior.

I am using identity plugin 1.0.0 from packagist

**Comment by HannesJo0139** [comment]
I can reproduce it. Did you do any further debugging? Maybe a small change could do the trick.

**Comment by mercury1337** [comment]
No, sorry - I'm no developer.

**Comment by HannesJo0139** [comment]
I've figured it out. Pull Request https://github.com/deflomu/Roundcube-SMTP-per-Identity-Plugin/pull/26 updates the server address scheme to how it is stored in Roundcube 1.6 Beta. Unfortunately the new maintainer has just applied these changes to the master branch without taking care of different versions.

Long story short: If you installed the plugin using git clone, just go into the plugin directory and execute 
```
git checkout 23f57b63d4cb0b3e24d7c2dbc4fea5977eaff730
```
This will revert all changes made after PR https://github.com/deflomu/Roundcube-SMTP-per-Identity-Plugin/pull/23. You will have to re-enter the smtp server addresses at identity settings and everything should work again.

**Comment by tihhgoncalves** [comment]
I was having the same problem and with the suggestion you gave I managed to make it work.
 Thanks a lot for the help! :)

**Comment by NotActuallyTerry** [comment]
Hey! Sorry about that, I didn't get pinged for this for some reason.
I've added tags through the repo for corresponding Roundcube versions, they should sync across to Packagist soon.
I'll leave this open until they do sync.

**Comment by HannesJo0139** [comment]
Nice, thank you 🙏

**Comment by NotActuallyTerry** [comment]
@deflomu Are you able to check why Packagist isn't pulling the new tags in?

**Comment by deflomu** [comment]
I think the tags cannot be parsed by packaging. They write here how version tags must look: https://packagist.org/about

**Comment by NotActuallyTerry** [comment]
Alright, I've updated the tags to follow semver (copying RC's major+minor to our major+minor) so they should sync over

**Comment by mercury1337** [comment]
Packagist still has the old package :-(

**Comment by NotActuallyTerry** [comment]
It appears to be synced over now! No idea why it took Packagist so long to pick up on them but oh well

**Comment by mercury1337** [comment]
Got "dev-master" from packagist today - still the same behavior :-(

**Comment by NotActuallyTerry** [comment]
My bad, I should've been a bit clearer, you'll want to pull version `1.5.0` from Packagist.

**Comment by mercury1337** [comment]
Thx a lot - it works now!
Thanks for all your hard work!

**Comment by HannesJo0139** [comment]
Please update the README with correct tags as well :)
`git checkout 1.0.0-1.6` => `git checkout 1.6.0`

**Comment by NotActuallyTerry** [comment]
Updated!

**Comment by Henri-J-Norden** [comment]
You might want to make it more obvious that the version number *must* correspond with your Roundcube version... Right now it is not even stated in the README and I had to read these github issues to figure out why it's not working... apparently iRedMail still ships with 1.5.2. I did not encounter such a problem installing the latest version of other plugins though, so I don't feel like this is an common/obvious way of doing things 😕
